/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.principal;

import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.registro.VentanaRegistroClientes;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.controlador.ClienteControlador;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.controlador.ReservaControlador;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.controlador.RestauranteControlador;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.registro.VentanaListadoReservasCliente;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.registro.VentanaListadoReservasRestaurante;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.registro.VentanaRegistroReserva;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.registro.VentanaRegistroRestaurantes;


/**
 *
 * @author ESTUDIANTE
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private VentanaRegistroRestaurantes ventanaRegistroRestaurantes;
    private VentanaRegistroClientes ventanaRegistroClientes;
    private VentanaListadoReservasRestaurante ventanaListadoReservasRestaurante;
    private VentanaListadoReservasCliente ventanaListadoReservasCliente;
    private VentanaRegistroReserva ventanaRegistroReserva;
    private ClienteControlador clienteControlador;
    private RestauranteControlador restauranteControlador;
    private ReservaControlador reservaControlador;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        RegistroMenu = new javax.swing.JMenu();
        registroClienteMenuItem = new javax.swing.JMenuItem();
        registroRestaurantesMenuItem = new javax.swing.JMenuItem();
        registroReservasMenuItem = new javax.swing.JMenuItem();
        listadoReservasClientesMenuItem = new javax.swing.JMenuItem();
        listadoReservasRestaurantesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        RegistroMenu.setText("Registro");

        registroClienteMenuItem.setText("Registro de clientes");
        registroClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroClienteMenuItemActionPerformed(evt);
            }
        });
        RegistroMenu.add(registroClienteMenuItem);

        registroRestaurantesMenuItem.setText("Registro de restaurantes");
        registroRestaurantesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroRestaurantesMenuItemActionPerformed(evt);
            }
        });
        RegistroMenu.add(registroRestaurantesMenuItem);

        registroReservasMenuItem.setText("Registro de reservas");
        registroReservasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroReservasMenuItemActionPerformed(evt);
            }
        });
        RegistroMenu.add(registroReservasMenuItem);

        listadoReservasClientesMenuItem.setText("Listado de reservas para clientes");
        listadoReservasClientesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoReservasClientesMenuItemActionPerformed(evt);
            }
        });
        RegistroMenu.add(listadoReservasClientesMenuItem);

        listadoReservasRestaurantesMenuItem.setText("Listado de reservas para restaurantes");
        listadoReservasRestaurantesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoReservasRestaurantesMenuItemActionPerformed(evt);
            }
        });
        RegistroMenu.add(listadoReservasRestaurantesMenuItem);

        jMenuBar1.add(RegistroMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroRestaurantesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroRestaurantesMenuItemActionPerformed
        if(ventanaRegistroRestaurantes == null){
            ventanaRegistroRestaurantes = new VentanaRegistroRestaurantes(restauranteControlador);
        }
        if(!ventanaRegistroRestaurantes.isVisible()){
            ventanaRegistroRestaurantes.setVisible(true);
            desktopPane.add(ventanaRegistroRestaurantes);
        }
    }//GEN-LAST:event_registroRestaurantesMenuItemActionPerformed

    private void registroClienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroClienteMenuItemActionPerformed
        if(ventanaRegistroClientes == null){
            ventanaRegistroClientes = new VentanaRegistroClientes(clienteControlador);
        }
        if(!ventanaRegistroClientes.isVisible()){
            ventanaRegistroClientes.setVisible(true);
            desktopPane.add(ventanaRegistroClientes);
        }
    }//GEN-LAST:event_registroClienteMenuItemActionPerformed

    private void listadoReservasRestaurantesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoReservasRestaurantesMenuItemActionPerformed
        if (ventanaListadoReservasRestaurante == null) {
        ventanaListadoReservasRestaurante = new VentanaListadoReservasRestaurante(restauranteControlador);
    }
    if (!ventanaListadoReservasRestaurante.isVisible()) {
        ventanaListadoReservasRestaurante.setVisible(true);
        desktopPane.add(ventanaListadoReservasRestaurante);
    }
    }//GEN-LAST:event_listadoReservasRestaurantesMenuItemActionPerformed

    private void listadoReservasClientesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoReservasClientesMenuItemActionPerformed
        if (ventanaListadoReservasCliente == null) {
        ventanaListadoReservasCliente = new VentanaListadoReservasCliente(clienteControlador);
    }
    if (!ventanaListadoReservasCliente.isVisible()) {
        ventanaListadoReservasCliente.setVisible(true);
        desktopPane.add(ventanaListadoReservasCliente);
    }
    }//GEN-LAST:event_listadoReservasClientesMenuItemActionPerformed

    private void registroReservasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroReservasMenuItemActionPerformed
        if(ventanaRegistroReserva == null){
            ventanaRegistroReserva = new VentanaRegistroReserva(reservaControlador);
        }
        if(!ventanaRegistroReserva.isVisible()){
            ventanaRegistroReserva.setVisible(true);
            desktopPane.add(ventanaRegistroReserva);
        }
    }//GEN-LAST:event_registroReservasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu RegistroMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listadoReservasClientesMenuItem;
    private javax.swing.JMenuItem listadoReservasRestaurantesMenuItem;
    private javax.swing.JMenuItem registroClienteMenuItem;
    private javax.swing.JMenuItem registroReservasMenuItem;
    private javax.swing.JMenuItem registroRestaurantesMenuItem;
    // End of variables declaration//GEN-END:variables
}
