/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.ordonezpenaloza.kelly.examenfinal.vista.registro;

import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.controlador.RestauranteControlador;
import ec.edu.ups.ordonezpenaloza.kelly.examenfinal.modelo.Reserva;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class VentanaListadoReservasRestaurante extends javax.swing.JInternalFrame {
    private RestauranteControlador restauranteControlador;
    /**
     * Creates new form VentanaListadoReservasRestaurante
     */
    public VentanaListadoReservasRestaurante(RestauranteControlador restauranteControlador) {
        this.restauranteControlador = restauranteControlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreRestaurante = new javax.swing.JLabel();
        txtNombreRestaurante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFechaReservacion = new javax.swing.JTextField();
        btnMostrarReservaciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservasRestaurantes = new javax.swing.JTable();

        lblNombreRestaurante.setText("Nombre del Restaurante");

        jLabel1.setText("Fecha Reservación");

        btnMostrarReservaciones.setText("Mostrar");
        btnMostrarReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReservacionesActionPerformed(evt);
            }
        });

        jLabel2.setText("Reservaciones");

        tblReservasRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblReservasRestaurantes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblNombreRestaurante)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreRestaurante)
                        .addComponent(txtFechaReservacion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarReservaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreRestaurante)
                    .addComponent(txtNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarReservaciones)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservacionesActionPerformed
        String nombreRestaurante = txtNombreRestaurante.getText();
    String fechaReservacion = txtFechaReservacion.getText();

    if (nombreRestaurante.isEmpty() || fechaReservacion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el nombre del restaurante y la fecha para buscar reservas.");
        return;
    }

    List<Reserva> reservas;
    try {
        reservas = restauranteControlador.buscarReservasPorNombreRestauranteFecha(nombreRestaurante, fechaReservacion);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al buscar reservas: " + e.getMessage());
        return;
    }

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Fecha");
    model.addColumn("Hora");
    model.addColumn("Número de personas");
    model.addColumn("Cliente");

    for (Reserva reserva : reservas) {
        model.addRow(new Object[]{reserva.getFecha(), reserva.getHora(), reserva.getNumeroPersonas(), reserva.getNombreCliente()});
    }

    tblReservasRestaurantes.setModel(model);
    }//GEN-LAST:event_btnMostrarReservacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarReservaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreRestaurante;
    private javax.swing.JTable tblReservasRestaurantes;
    private javax.swing.JTextField txtFechaReservacion;
    private javax.swing.JTextField txtNombreRestaurante;
    // End of variables declaration//GEN-END:variables
}
